"""
APK Signing Proxy Bot - SAFE VERSION
=====================================
Credentials loaded from environment variables ONLY. Never hardcode them.

Required environment variables:
    BOT_TOKEN      - From @BotFather
    API_ID         - From my.telegram.org (number)
    API_HASH       - From my.telegram.org (string)
    SIGNER_BOT     - Username of the signer bot e.g. @apksignerbot
    SESSION_STRING - Generated by generate_session.py on your PC
"""

import asyncio
import os
import logging
from telethon import TelegramClient, events
from telethon.sessions import StringSession
from telegram import Bot
from telegram.ext import Application, MessageHandler, ContextTypes, filters

# ── All credentials from environment — NEVER hardcode ──
BOT_TOKEN      = os.environ["BOT_TOKEN"]
API_ID         = int(os.environ["API_ID"])
API_HASH       = os.environ["API_HASH"]
SIGNER_BOT     = os.environ.get("SIGNER_BOT", "@apksignerbot")
SESSION_STRING = os.environ["SESSION_STRING"]

logging.basicConfig(format="%(asctime)s - %(levelname)s - %(message)s", level=logging.INFO)
logger = logging.getLogger(__name__)

pending_requests: dict = {}
user_client = TelegramClient(StringSession(SESSION_STRING), API_ID, API_HASH)


async def handle_user_apk(update, context: ContextTypes.DEFAULT_TYPE):
    user_id  = update.effective_user.id
    document = update.message.document

    if not document.file_name.lower().endswith(".apk"):
        await update.message.reply_text("❌ Please send a valid .apk file.")
        return

    await update.message.reply_text(
        f"📦 Received *{document.file_name}*\n⏳ Forwarding to signer bot...",
        parse_mode="Markdown"
    )

    file       = await context.bot.get_file(document.file_id)
    local_path = f"/tmp/{document.file_id}_{document.file_name}"
    await file.download_to_drive(local_path)
    await send_to_signer_bot(user_id, local_path, document.file_name)


async def send_to_signer_bot(user_id: int, file_path: str, filename: str):
    try:
        msg = await user_client.send_file(SIGNER_BOT, file_path, caption=f"Sign this APK: {filename}")
        pending_requests[msg.id] = {"user_id": user_id, "filename": filename}
        logger.info(f"Sent APK → signer bot | msg_id={msg.id} | user={user_id}")
    except Exception as e:
        bot = Bot(BOT_TOKEN)
        await bot.send_message(chat_id=user_id, text=f"❌ Error contacting signer bot:\n{e}")
    finally:
        if os.path.exists(file_path):
            os.remove(file_path)


@user_client.on(events.NewMessage(from_users=SIGNER_BOT))
async def handle_signer_reply(event):
    bot = Bot(BOT_TOKEN)

    if event.document:
        if not pending_requests:
            return
        latest_key  = max(pending_requests.keys())
        request     = pending_requests.pop(latest_key)
        signed_path = f"/tmp/signed_{event.document.id}.apk"
        await event.download_media(signed_path)
        await bot.send_document(
            chat_id=request["user_id"],
            document=open(signed_path, "rb"),
            filename=f"signed_{request['filename']}",
            caption="✅ Your APK has been signed successfully!"
        )
        if os.path.exists(signed_path):
            os.remove(signed_path)

    elif event.text and pending_requests:
        latest_key = max(pending_requests.keys())
        request    = pending_requests.get(latest_key)
        if request:
            await bot.send_message(chat_id=request["user_id"], text=f"ℹ️ Signer bot says:\n{event.text}")


async def main():
    await user_client.connect()
    logger.info("✅ Telethon session connected!")

    app = Application.builder().token(BOT_TOKEN).build()
    app.add_handler(MessageHandler(filters.Document.ALL, handle_user_apk))

    await app.initialize()
    await app.start()
    await app.updater.start_polling()
    logger.info("🤖 Bot is live!")

    await user_client.run_until_disconnected()

    await app.updater.stop()
    await app.stop()
    await app.shutdown()


if __name__ == "__main__":
    asyncio.run(main())
